name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code into the runner
      - name: Checkout repository code into runner
        uses: actions/checkout@v2

      # Set up the Python environment with version 3.10
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Zorg ervoor dat dit tussen aanhalingstekens staat

      # Clear pip cache
      - name: Clear pip cache
        run: rm -rf ~/.cache/pip

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run flake8 to check code quality
      - name: Run flake8 to check code quality
        run: |
          pip install flake8
          flake8 main.py

  delivery:
    runs-on: ubuntu-latest
    needs: test  # Ensure this job only runs after the test job succeeds

    steps:
      # Checkout the repository code into the runner
      - name: Checkout repository code into runner
        uses: actions/checkout@v2

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/python-api-devops:latest .

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Push the image to Docker Hub
      - name: Push the image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/python-api-devops:latest
